# 💡예외 처리
## 📌1. 예외 처리
### 1-1 오류(error)와 예외(exception)
> 자바 프로그램에서 문법에 맞지않는 코드를 작성한다면, 문법 오류를 발생시킨다.
> 또한 맞는 문법으로 작성하더라도 예상하지 못한 오류가 발생할 수 있다.
> 이러한 상황을 크게 오류와 예외로 나눈다.
>
> 오류는 개발자가 예측할 수 없는 프로그램 문제이므로, 오류에 대한 처리는 불가능하다.
>
> 하지만 예외는 발생할 수 있는 상황을 미리 예측하려여 처리 할 수 있다.
> 따라서 예외처리를 하는 법을 알아보자.

### 1-2 예외 처리(exception handling
자바에서 예외 처리는 try / catch / finally 문을 사용할 수 있다.
>문법
>try {
>예외를 처리하길 원하는 실행 코드;
>} catch (e1) {
>e1 예외가 발생할 경우에 실행될 코드;
>} catch (e2) {
>e2 예외가 발생할 경우에 실행될 코드;
>}
>...
>finally {
>예외 발생 여부와 상관없이 무조건 실행될 코드;
>}

- try 블록: 기본적으로 맨 먼저 실행되는 코드로 여기에서 발생한 예외는 catch 블록에서 처리한다.
- cahch 블록 : try 블록에서 발생한 예외 코드나 예외 객체를 인수로 전달받아 그 처리를 담당한다.
- finally 블록 : try 블록에서 예외가 발생하는지 여부에 상관없이 맨 마지막에 실행된다.

### 1-3 예외처리 매커니즘
![](https://velog.velcdn.com/images/rkddntjd7/post/72f01c1f-4e0b-4b0f-9033-5645509eaf09/image.png)
출처 : http://www.tcpschool.com/java/java_exception_intro

만약 1번 try 블록에서 예외가 발생하지 않고, 바깥쪽 try 블록에서도 예외가 발생하지 않으면, 6번 finally 블록이 실행된다. 하지만 1번 블록에서 예외가 발생하면 2번 3번 catch 블록에서 예외처리를 할 수 있는지 검사한다. 적절한 블록이 없다면, 바깥쪽 try 블록의 4번, 5번 catch 블록을 검사한다. 이 과정에서 적절한 catch 블록을 찾는다면 그 블록을 실행한 후 6번 finally 블록을 실행한다. 만약 적절한 catch 블록이 어디에도 없다면, 프로그램은 강제 종료한다.

## 📌2. Exception 클래스
>자바에서 모든 예외의 조상 클래스가 되는 Exception 클래스는 크게 RuntimeException과 그 외의 Exception 클래스의 자식 클래스로 구분된다. RuntimeException 클래스를 상속받는 자식 클래스들은 주로 큰 문제를 일으키지않는 예외들이다. 따라서 try / cath 문을 잘 사용하지않는다.
>
>하지만 Exception 클래스에 속하는 자식 클래스들은 치명적인 예외 상황을 발생시키므로, try / catch 문을 사용하여 예외처리를 해주는것이 좋다.

## 📌3. 예외 발생 및 회피
### 3-1 예외 발생시키기
자바에서 throw 키워드를 사용하여 예외를 발생시킬 수 있디.
```java
Exception e = new Exception("오류메시지");

...

throw e;
```
위에서 생성한 문자열은 getMessage() 메소드를 사용하여 오류메시지로 출력할 수 있다.
### 3-2 예외 회피하기
메소드 선언부에 throws 키워드를 사용하여 해당 메소드를 사용할 때 발생할 수 있는 예외를 미리 명시할 수 있다.
```java
public class Exception04 {

    static void handlingException() throws Exception { throw new Exception(); }

    public static void main(String[] args) {
        try {
            handlingException();
            
        } catch (Exception e) {
        
            System.out.println("main() 메소드에서 예외가 처리됨!");
        }
    }
}
```
위와 같이 try / catch 문을 생략이 가능하다.

